### ISSUE TITLE
Selecting a reset button doesn't clear as one would expect

### ISSUE THREAD

**Issue by softwarespot** [jpederson/Squirrel.js#10]
The issue is because this...

``` javascript
elem.find('input[type=clear]').click(function() {
```

``` javascript
elem.find('input[type=reset]').click(function() {
```

**Comment by jpederson** [comment]
This is set as of your pull request, but I added back in support for `input[type=reset]` since it's a valid tag and is used by several legacy (and modern) apps. So both/either will work now.

**Comment by softwarespot** [comment]
Good point. Thanks for noticing.

**Comment by jpederson** [comment]
Thank you for noticing my oversight in the first place hah! I really appreciate the contributions a ton, and hope you're happy with the state of the script right now.

**Comment by softwarespot** [comment]
No problem. It was a toss up between your library and another one. I felt your library had potential and it was so easy to understand =)

PS There is still a bug with data-squirrel
