### ISSUE TITLE
If element doesn't have a name then it should default to id

### ISSUE THREAD

**Issue by softwarespot** [jpederson/Squirrel.js#16]
Failing that it won't be stored.

Edit: I can create a PR, but wanted to get your take on this first.

**Comment by jpederson** [comment]
I like this idea as well, and would be interested to see how you'd implement it. So we would drop the `[name]` selector from all the fields and then just do some logic inside the `elem.each()` to check for name, then ID, and if all else fails, then null it and don't process null field name/ids? Just clarifying - want to make sure it doesn't end up doubling our field selections with name for one and id for another. Make sense?

**Comment by softwarespot** [comment]
" ...to check for name, then ID, and if all else fails, then null it and don't process null field name/ids?"
That's correct.

I decided to scrap my original idea, when I read your note about doubling field selection. I will probably look at this tomorrow evening now.

**Comment by softwarespot** [comment]
Some ideas I had >> http://jsbin.com/lumapevuha/edit?html,js,console

**Comment by softwarespot** [comment]
[This](https://github.com/softwarespot/squirrel-beta.js/blob/master/jquery.squirrel.js) version includes the request above as well as this one #21. What do you think @jpederson and @fmp777?

**Comment by flxmrk** [comment]
Hmm didn't test that, but wouldn't you be selecting doubles if an element has BOTH name and ID?

I'm not sure about fallback to ID - since the standard is that a form element without name will not be submitted with the form data.  Typically I'll have form elements with ID but no name, and they are more functional elements, not data to be filled by end user.

What is the use case to fallback to id?  why would someone have a form with all id's but no names, and need it restored?

Here's a fiddle that shows the concept that form elements without names don't get passed
http://jsfiddle.net/uks9zmon/

**Comment by softwarespot** [comment]
[Mine](http://jsfiddle.net/arg5ak9k/) I am using val() as removing text from the textarea and then submitting again, didn't work.

You're right, but as squirrel can be effectively applied to anything that isn't a form, but still contain input elements, I feel this is worthy of considering. I also suspect not everyone is going to following the convention you and I would use i.e. having  a name attribute for proper serialization. In fact a project I took over from (I will tell more for another day), weren't using a form element in anyway, even though they had something like 6-7 "forms". In actual fact they made things super difficult by doing something like this for every form...

``` javascript
$('#submit-button').click(function () {
    // NOT MY CODE! BUT A SIMPLE REPRESENTATION OF THE STYLE THEY USED
    var data {};

    data['something'] = $('#some-input').val();
    data['something else'] = $('#some-input-again').val();

    // ... Ajax submit
});
```

So there are people out there who like to make things difficult! =)

**Comment by flxmrk** [comment]
_chuckle_ fair enough  extract forms data very manually and process it.

But still yet, wouldn't the proposed solution select the same form element twice if it had both name and id?  therefore double process the element?

**Comment by softwarespot** [comment]
You chuckle, I have been crying!

No, the code checks if a name attribute exists and if it does processes it with the name, otherwise it check if an id exists and failing that doesn't do anything.

Edit: You're right actually. I didn't think about it until now. Perhaps I should temporarily store in an array as being processed. What do you think?

**Comment by softwarespot** [comment]
Actually no it doesn't as the filter appears to take care of this. Add this...

``` javascript
                           // a named attribute is required to store the element data.
                            if (name === undefined) {
                                return;
                            }
                            console.log(this.tagName + ', '+ name)
```

and you will see that it only displays once. I have updated the beta example by the way.

**Comment by flxmrk** [comment]
Ahh quite right, filter is smart enough to not select 2 of same element.

Looks good to me then!

**Comment by softwarespot** [comment]
Yeh, lucky coincidence first, until I re-read the documentation.
