### ISSUE TITLE
Certain form fields should not be stored (ie credit card number)

### ISSUE THREAD

**Issue by flxmrk** [jpederson/Squirrel.js#18]
Would be good to add a flag to a form field to exclude it from the storage.

Credit Card numbers should not be there, and any other sensitive data a person might have in a form.

Maybe something like 

``` html
<input type="text" name="ccnum" data-squirrel-nosave="true">
```

or

``` html
<input type="text" name="ccnum" class="squirrel-nosave">
```

would work.

**Comment by softwarespot** [comment]
I like the idea.

**Comment by jpederson** [comment]
Added support for `squirrel-ignore` class in https://github.com/jpederson/Squirrel.js/commit/a0f14de1060b8b3a5d6d335740536743eec596af
