### ISSUE TITLE
Email field not saved

### ISSUE THREAD

**Issue by michelemarrionline** [jpederson/Squirrel.js#2]
Hi man!

i love this script. used perfectly, but a little issue. The email input won't save.

u know why? security reasons?

**Comment by michelemarrionline** [comment]
and radio boxes too

**Comment by jpederson** [comment]
Resolved issue with email field type not working:
https://github.com/jpederson/Squirrel.js/commit/6a83bb54f0ba747cfe9d9a4734845c28c7b45d5f

And added a test radio field to confirm it works (tested in Chrome, Firefox, and IE9):
https://github.com/jpederson/Squirrel.js/commit/7ebcb03093169b6257ad60c2b629a61989e75a2b

**Comment by jpederson** [comment]
How's that? :smile:

**Comment by michelemarrionline** [comment]
love u man.

testing right now.

seems email’s working.

radio no.

:)

---

michelemarri http://michelemarri.me/.me http://michelemarri.me/
michelemarrionline@gmail.com mailto:michelemarrionline@gmail.com
skype: michelemarrionline

Informativa ai sensi del DLgs 196/2003 (Codice Privacy)
Le informazioni contenute nella presente e-mail e negli eventuali allegati, devono essere nella disponibilità del solo destinatario. Chiunque venga in possesso non autorizzato di questa e-mail è vincolato dalla Legge a non leggerne il contenuto, a non copiarla, a non diffonderla su Facebook e a non usarla come ricatto.

**Comment by jpederson** [comment]
May I see your code? Also, what browser are you viewing in? I added radio buttons to the index file (shows on squirreljs.com) - do those work for you there? They do for me, so I guess I need some other information for my testing.

James

**Comment by michelemarrionline** [comment]
my fault. all working now. thanks man. a lot ;)

**Comment by jpederson** [comment]
Not a problem! Have a great day!
