### ISSUE TITLE
It's common practice to prefix variables referencing jQuery objects with $

### ISSUE THREAD

**Issue by softwarespot** [jpederson/Squirrel.js#20]
What does everyone think?

**Comment by jpederson** [comment]
I think that's fair now that I really think about it, hah.. You want to implement, or should I?

**Comment by softwarespot** [comment]
I can do it.

**Comment by jpederson** [comment]
Cool, have fun, and thanks!

**Comment by softwarespot** [comment]
I liked your renaming of elem => form. Good choice I would say =)
