### ISSUE TITLE
Restore form in DOM order?

### ISSUE THREAD

**Issue by flxmrk** [jpederson/Squirrel.js#21]
Right now the form restoration happens based on order in DOM but due to selectors, it does all inputs (text types) & textareas, then selects, then radios, then checkboxes. 

I did just now run into an issue now that we have the new trigger('change') code in place.

In a form that dynamically updates based on previous form values, if we don't restore in the order the elements exist in the DOM, then certain values like 

``` javascript
$('option[value="test value"]')
```

may not exist at the time it is called.

Restore in order of DOM would likely solve this issue for MOST cases where the DOM is clean and well-structured.  I think it'd be a good default.

Alternately, could give control to end user by going in order of tabindex if available, otherwise DOM order.

I realize this would considerably change the codebase, and perhaps its outside the scope of this project to support dynamic forms, but if you were to do it, it might look something like this:

``` javascript
var $formfields = form.find('*').filter('input[name],textarea[name],select[name]');
$formfields.each(function(){
    var $this = $(this), 
        tag = this.tagName;
    switch (tag)
    {
        case 'input':
            var type = $this.attr('type');
            if (type === 'checkbox') {
                // checkbox logic here
            } else
            if (type === 'radio') {
                // radio logic here
            } else
            {
                // normal text field logic here
            }

            break;
        case 'select':
            // select logic here
            break;
        case 'textarea':
            // textarea logic here
            break;
    }
});
```

what do you guys think?

**edit** the above code doesn't reflect integration of tabindex option

**Comment by softwarespot** [comment]
Just for the benefit of me only, could you provide an example of what you mean by dynamic form? As I tested by adding a text input and option to the select, with no problem. It's just for my understanding that's all.

**Comment by flxmrk** [comment]
![image](https://cloud.githubusercontent.com/assets/2659615/8786903/357736a0-2eee-11e5-915c-c74cf9e41ae4.png)

Like in this case, the first select populates the second select.

But actually produces an error while squirrel is trying to restore due to <option value="that value"></option> not even being in the DOM yet.

**Comment by softwarespot** [comment]
Got it. I would definitely welcome such a change. Are you thinking about adding a new action line 'refresh' or 'restart'? This would require some kind of logical re-write.

It's been a long day, so it finally clicked what you meant.

**Comment by flxmrk** [comment]
hmm just realized that this may not achieve the desired goal.  while the onchange event is fired for the previous form field, that event is asynchronous, so its not likely to have populated the next select before squirrel was done restoring data.

Though, it may still yet solve other use cases anyway!  Here's the code that works (based on commit a0f14de1060b8b3a5d6d335740536743eec596af):

``` javascript
                    // LOAD VALUES FOR ALL FORMS FROM SESSION STORAGE IN ORDER OF DOM
                    var $formfields = form.find('*').filter('input[name],textarea[name],select[name]');
                    $formfields.each(function(){
                        var elem = $(this);
                        switch (this.tagName.toLowerCase())
                        {
                            case 'input':
                                var type = elem.attr('type');
                                if (type === 'checkbox') {
                                    var chkval = elem.attr('value');
                                    if (typeof chkval !== 'string') {
                                        chkval = '';
                                    }

                                    var value = stash(storage_key, elem.attr('name') + chkval);
                                    if (value !== null && value !== this.checked) {
                                        this.checked = (value === true);
                                        elem.trigger('change');
                                    }
                                } else
                                if (type === 'radio') {
                                    var value = stash(storage_key, elem.attr('name'));
                                    if (value !== null && value !== this.checked) {
                                        this.checked = (elem.val() === value);
                                        elem.trigger('change');
                                    }
                                } else
                                {
                                    // load text values from session storage
                                    var value = stash(storage_key, elem.attr('name'));
                                    if (value !== null && !elem.is('[readonly]') && elem.is(':enabled') && elem.val() !== value) {
                                        elem.val(value).trigger('change');
                                    }
                                }

                                break;
                            case 'select':
                                // select logic here
                                var value = stash(storage_key, elem.attr('name'));
                                if (value !== null) {
                                    // if value is not enumerable then make it enumerable. Then for each value in the array, find the option
                                    // with that value and set the property called selected to true
                                    $.each(typeof(value) !== 'object' ? [value] : value, function(index, option) {
                                        elem.find('option[value=' + option + ']:not(:checked)').prop('selected', true).trigger('change');
                                    });
                                }
                                break;
                            case 'textarea':
                                // load text values from session storage
                                var value = stash(storage_key, elem.attr('name'));
                                if (value !== null && !elem.is('[readonly]') && elem.is(':enabled') && elem.val() !== value) {
                                    elem.val(value).trigger('change');
                                }
                                break;
                        }
                    });
```

**Comment by flxmrk** [comment]
Oh wow, nevermind, i guess its not async?  I just tested this code and it actually solved the problem :)

**Comment by softwarespot** [comment]
This code is up to date with commit 08c2057

``` javascript
// LOAD VALUES FOR ALL FORMS FROM SESSION STORAGE IN ORDER OF DOM
var $formfields = $form.find('*').filter('input[name], textarea[name], select[name]');
$formfields.each(function() {
    var $elem = $(this);
    switch (this.tagName.toLowerCase()) {
        case 'input':
            var type = $elem.attr('type');
            if (type === 'checkbox') {
                var chkval = $elem.attr('value');
                if (typeof chkval !== 'string') {
                    chkval = '';
                }

                var value = stash(storage_key, $elem.attr('name') + chkval);
                if (value !== null && value !== this.checked) {
                    this.checked = (value === true);
                    $elem.trigger('change');
                }

            } else if (type === 'radio') {
                var value = stash(storage_key, $elem.attr('name'));
                if (value !== null && value !== this.checked) {
                    this.checked = ($elem.val() === value);
                    $elem.trigger('change');
                }

            } else {
                // load text values from session storage
                var value = stash(storage_key, $elem.attr('name'));
                if (value !== null && !$elem.is('[readonly]') && $elem.is(':enabled') && $elem.val() !== value) {
                    $elem.val(value).trigger('change');
                }

            }
            break;

        case 'select':
            // select logic here
            var $elem = $(this),
                value = stash(storage_key, $elem.attr('name'));
            if (value !== null) {
                $elem.find('option:not(:checked)').filter(function(option) {
                    var $option = $(this);
                    return ($option.val() === option || $option.html() === option);
                }).prop('selected', true).trigger('change');
            }
            break;

        case 'textarea':
            // load text values from session storage
            var value = stash(storage_key, $elem.attr('name'));
            if (value !== null && !$elem.is('[readonly]') && $elem.is(':enabled') && $elem.val() !== value) {
                $elem.val(value).trigger('change');
            }
            break;
    }
});
```

Do you still have the example you tested with?

**Comment by softwarespot** [comment]
Something like this >> http://jsfiddle.net/q3dk934x/?

I'll be honest, jQuery and JS in general are not something I work with on a daily basis, as I come from a C#/Java/AutoIt background.

**Comment by flxmrk** [comment]
Sorry missed your question about the example  Not quite like your example, more like this:
http://jsfiddle.net/teqho196/1/

**Comment by softwarespot** [comment]
Thanks @fmp777. I will do some testing and wait for @jpederson  to respond, to see if this is something that should be included.

**Comment by softwarespot** [comment]
I couldn't really see/understand your enhancement if I am honest. What I did was create a beta version [here](https://github.com/softwarespot/squirrel-beta.js) with your changes merged with the [last commit](d3286a7) of the plugin to understand the benefits. The example works with both the beta and stable version. Could you maybe provide an example that would break the stable library, but doesn't in the beta. Thanks =)

**Comment by flxmrk** [comment]
Its a very specific case, and wouldn't affect EVERY dynamic form (it doesn't break on the jsfiddle i provided).

But to understand WHEN it breaks is easy - easier than writing up a fiddle for it :smirk:

Right now squirrel selects & restores all elements essentially at random

``` javascript
                        $form.find('input[type=color][name], input[type=date][name], input[type=datetime][name], input[type=datetime-local], input[type=email][name], input[type=month][name], input[type=number][name], input[type=range][name], input[type=search][name], input[type=tel][name], input[type=text][name], input[type=time][name], input[type=url][name], input[type=week][name], textarea[name]').each(function() {

                        // set select values on load.
                        $form.find('select[name]').each(function() {

                        // radio buttons.
                        $form.find('input[type=radio][name]').each(function() {

                        $form.find('input[type=checkbox][name]').each(function() {
```

What if one of those RADIO buttons actually populates a SELECT field?  Too bad, your select didn't exist when it tried to populate the value, so thats life, get over it, this form saver doesn't like your fancy dynamic form :unamused: 

If you simply restore the form fields by order of DOM (and thus trigger their change events) - then you are very likely going to avoid issues with dynamic forms which have logic written to EXPECT the onchange events to be fired in the order the form is displayed.

There are rare cases where the DOM order will not reflect the presentational order, and thus some dynamic forms might still have issues.  But my proposed solution doesn't go here.

**Comment by softwarespot** [comment]
What an idiot I am, now I understand what you mean. You're right it's a rare scenario, but one which I feel this plugin should still avoid. I will give it a couple of days for @jpederson to say their thoughts, before committing the changes. As no doubt it will probably result in a new release.
