### ISSUE TITLE
Next release v0.1.7

### ISSUE THREAD

**Issue by softwarespot** [jpederson/Squirrel.js#23]
This is the current changelog for the next release. I am happy to release, but feel it's beyond my role as a collaborator.

Fixes:
- Missing license in package.json.
- Overriding default options with the options temporarily passed to squirrel. To override the default options, use $.fn.squirrel.options.[OPTION] instead.

Improvements:
- Added using an id attribute if a name attribute doesn't exist. A name attribute is the recommended approach though for forms.
- Using .on() instead of event aliases for the likes of click and submit, as well as using the namespace "squirrel.js". This allows us specific targeting of the events created by Squirrel.js, instead of just using a generic "click" event.
- Changed updating of a form based on the DOM order, therefore offering support for dynamic forms.
- Added the 'stop' action, which destroys the  events assigned to the form by Squirrel.js.
- Various readability tweaks and efficiency improvements.
- Updated the example showcasing the following additions.

**Comment by softwarespot** [comment]
Added appropriate information to the documentation

**Comment by jpederson** [comment]
Bumped version numbers in repo, published to npm, and added release tag on github to release on bower. Thanks, man!

**Comment by softwarespot** [comment]
Thanks for doing that. I didn't want to take over the project too much =)
