### ISSUE TITLE
Type Error on using squirrel.js

### ISSUE THREAD

**Issue by arvinddoraiswamy** [jpederson/Squirrel.js#24]
Thanks for this plugin :)

I have a Rails app and am trying to use this. I added the squirrel class to my form and I see that there. I used the JQuery URL that you had in the documentation too, and that seems to load as well. And then copied squirrel.js too and that too gets loaded.

But then I look at the console when the page loads and I get this.

**20:19:58.632 TypeError: $(...).squirrel is not a function1 jquery.squirrel.js:274:4**

I am not sure why as I am not good at Jquery at all and am just using the plugin :). Can you help me debug this or is this an actual bug?

I am using Firefox on Ubuntu 14.04 if that's any help.

**Comment by arvinddoraiswamy** [comment]
And FWIW same thing on Chrome as well

**Uncaught TypeError: $(...).squirrel is not a function**

This is the JQuery version I am using in my HTML - **//code.jquery.com/jquery-1.11.3.min.js**

**Comment by softwarespot** [comment]
I am using the current version of Squirrel.js (which I have been updating as of recent) in a production version of my application and haven't see this error. Do you see it in the example? I suspect you're calling .squirrel() before the plugin has been loaded. Remember a browser loads a page top down.

**Comment by arvinddoraiswamy** [comment]
This page for example seems to work perfectly - http://squirreljs.com/. And I just loaded the example as well and that works fine too.

How can I ensure that the plugin loads first?

**Comment by softwarespot** [comment]
Could you perhaps provide a JSFiddle example of your webpage so I can look at it?

**Comment by arvinddoraiswamy** [comment]
Its really just a very simple page with a few input fields and a submit
button that submits feedback. I do have the "class= squirrel" in the form
as well.

On Sat, Aug 1, 2015 at 12:30 AM, SoftwareSpot Apps <notifications@github.com

**Comment by arvinddoraiswamy** [comment]
I think you are right though on the page load stuff. Let me try comparing
the example and my form and see if I can figure it out. Thanks so much for
your help :)

**Comment by softwarespot** [comment]
If you fix it please close the issue. Thanks

**Comment by arvinddoraiswamy** [comment]
Yes moving and force loading squirrel.js before others seems to make the
error vanish. This is not a bug but just some stupidity on my part and some
Rails magic :). This closes Issue #24.

On Sat, Aug 1, 2015 at 12:43 AM, SoftwareSpot Apps <notifications@github.com
