### ISSUE TITLE
v0.1.8

### ISSUE THREAD

**Issue by softwarespot** [jpederson/Squirrel.js#27]
Not quite ready for a release, but documenting the changes and additions that have taken place since v0.1.7.
- Added 'off' and 'remove' aliases for 'stop' and 'clear' actions.
- Added to the storage_method option the ability to pass a valid storage object reference. It now accepts either local or session strings; otherwise, a storage object reference that has the functions getItem(), removeItem() and setItem() can be passed for usage instead. Useful if you're supporting browsers with a custom storage-like polyfill. Default is 'local'
- Added the option storage_key_prefix to prefix a string to the storage key. This option is useful if you're using the likes of data-squirrel="" instead of adding the class squirrel, as you can add a prefix without having to include in every attribute value. Default is empty
- Improved JSHint configuration for cleaner, efficient code.
- Fixed scope of onload function.
- Removed deprecated version number field from bower.json.

**Comment by softwarespot** [comment]
I am happy with this changelog for the next version

**Comment by jpederson** [comment]
Me too - sorry for the delay. I'll do a release today.

**Comment by softwarespot** [comment]
Thank you

**Comment by softwarespot** [comment]
What is your procedure for uploading to bower and npm? Just curious as right now when I release I just do it on github. Do you use any scripts?

**Comment by jpederson** [comment]
I just make sure the bower.json and package.json have the same version
number. And then I do a new release with notes in Github (that handles
Bower publication). For npm, at the moment, only my username can run the
'npm publish' command, but I'll be working on that.

Also, crap, I forgot to push the new version on Wednesday... Sorry. Pushing
now.

Best,
James

**Comment by softwarespot** [comment]
But you still had to register with bower.io beforehand?

Don't worry about the release =)

**Comment by jpederson** [comment]
With Bower, you register initially with a repository URL, and then every time you visit the "Releases" tab in Github, you can push a new release, and as long as bower.json has the next version number in the repo, it will release the newest version to Bower.

**Comment by jpederson** [comment]
New release published to both bower and npm.

**Comment by softwarespot** [comment]
Cool got it. I have never used bower register until now.

**Comment by jpederson** [comment]
Correction - Bower takes its version number from the one you put into Github, there's no version number in bower.json - not sure how I got confused on that. But yeah, npm requires the new version number in the package.json file in order to publish, but I also have to add a user to the npm registry to enable you to publish new releases there.

**Comment by softwarespot** [comment]
I will leave releases up to you methinks. 

I don't have any plans for the next month or so to add anything new to this plugin. Though I would like to see (for personal enjoyment only) porting over to ES2015 (see note I left in the code). Though I wouldn't push to the master branch.

NOTE: I would use a transpiler of course to convert to ES5
