### ISSUE TITLE
Checkbox bug

### ISSUE THREAD

**Issue by mattyp** [jpederson/Squirrel.js#4]
Hey there, I discovered that the code used for stashing the state of text boxes didn't work for my form. This is because it is getting the `.val()` of the checkbox, rather than the 'checked' property. I've updated mine locally with the following variation to the field update event function:

``` Javascript
elem.find("input, select, textarea").on( 'blur keyup change', function() {
    stash( $(this).attr("name"), this.type=="checkbox" ? $(this).prop('checked') : $(this).val());
});
```

The comparitor/setter for checkboxes now looks like this:

``` Javascript
elem.find("input[type=checkbox][name]").each(function(){
    var value = stash( $(this).attr( "name" ) );
    if ( value !== null ) {
        this.checked = ( value == true );
    }
});
```

Thought you might like to know.

Cheers,
Matt,

**Comment by jpederson** [comment]
I'll be digging in on this fix at some point in the next couple days - if I can get dug out from under this ridiculous amount of work I have going on. This is definitely on my radar though, and thanks for bringing it to my attention!

**Comment by softwarespot** [comment]
Thanks @mattyp
