### ISSUE TITLE
readonly default value getting cleared

### ISSUE THREAD

**Issue by chris-mackie** [jpederson/Squirrel.js#6]
I have a project id already set into a readonly text input but when using squirrel the value gets cleared?

Also using http://jqueryvalidation.org/ incase there are known conflicts but there are no errors coming up in the console?

**Comment by jpederson** [comment]
Oh, hadn't thought of this - it stores values when a field changes or is typed in. If a field is disabled and has an initial value, it doesn't store it, and so when it refills it on load, it empties it. My apologies! I'll get an update pushed later today to exclude disabled fields from being manipulated by the script.

**Comment by softwarespot** [comment]
``` html
<input type="text" name="user" value="some_random_user" readonly />
```

I see no issue with the above input. Unless I misunderstood, which if I did then sorry, otherwise; no bug.
